-- Seed: Dữ liệu hành chính Hà Nội
-- Source: https://github.com/kenzouno1/DiaGioiHanhChinhVN
-- Generated automatically — DO NOT EDIT manually

-- Province
INSERT INTO public.vn_provinces (id, name) VALUES ('01', 'Thành phố Hà Nội') ON CONFLICT (id) DO NOTHING;

-- Districts
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('001', 'Quận Ba Đình', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('002', 'Quận Hoàn Kiếm', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('003', 'Quận Tây Hồ', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('004', 'Quận Long Biên', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('005', 'Quận Cầu Giấy', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('006', 'Quận Đống Đa', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('007', 'Quận Hai Bà Trưng', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('008', 'Quận Hoàng Mai', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('009', 'Quận Thanh Xuân', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('016', 'Huyện Sóc Sơn', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('017', 'Huyện Đông Anh', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('018', 'Huyện Gia Lâm', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('019', 'Quận Nam Từ Liêm', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('020', 'Huyện Thanh Trì', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('021', 'Quận Bắc Từ Liêm', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('250', 'Huyện Mê Linh', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('268', 'Quận Hà Đông', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('269', 'Thị xã Sơn Tây', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('271', 'Huyện Ba Vì', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('272', 'Huyện Phúc Thọ', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('273', 'Huyện Đan Phượng', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('274', 'Huyện Hoài Đức', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('275', 'Huyện Quốc Oai', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('276', 'Huyện Thạch Thất', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('277', 'Huyện Chương Mỹ', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('278', 'Huyện Thanh Oai', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('279', 'Huyện Thường Tín', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('280', 'Huyện Phú Xuyên', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('281', 'Huyện Ứng Hòa', '01') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_districts (id, name, province_id) VALUES ('282', 'Huyện Mỹ Đức', '01') ON CONFLICT (id) DO NOTHING;

-- Wards
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00001', 'Phường Phúc Xá', 'Phường', '001') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00004', 'Phường Trúc Bạch', 'Phường', '001') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00006', 'Phường Vĩnh Phúc', 'Phường', '001') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00007', 'Phường Cống Vị', 'Phường', '001') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00008', 'Phường Liễu Giai', 'Phường', '001') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00013', 'Phường Quán Thánh', 'Phường', '001') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00016', 'Phường Ngọc Hà', 'Phường', '001') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00019', 'Phường Điện Biên', 'Phường', '001') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00022', 'Phường Đội Cấn', 'Phường', '001') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00025', 'Phường Ngọc Khánh', 'Phường', '001') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00028', 'Phường Kim Mã', 'Phường', '001') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00031', 'Phường Giảng Võ', 'Phường', '001') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00034', 'Phường Thành Công', 'Phường', '001') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00037', 'Phường Phúc Tân', 'Phường', '002') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00040', 'Phường Đồng Xuân', 'Phường', '002') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00043', 'Phường Hàng Mã', 'Phường', '002') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00046', 'Phường Hàng Buồm', 'Phường', '002') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00049', 'Phường Hàng Đào', 'Phường', '002') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00052', 'Phường Hàng Bồ', 'Phường', '002') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00055', 'Phường Cửa Đông', 'Phường', '002') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00058', 'Phường Lý Thái Tổ', 'Phường', '002') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00061', 'Phường Hàng Bạc', 'Phường', '002') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00064', 'Phường Hàng Gai', 'Phường', '002') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00067', 'Phường Chương Dương', 'Phường', '002') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00070', 'Phường Hàng Trống', 'Phường', '002') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00073', 'Phường Cửa Nam', 'Phường', '002') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00076', 'Phường Hàng Bông', 'Phường', '002') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00079', 'Phường Tràng Tiền', 'Phường', '002') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00082', 'Phường Trần Hưng Đạo', 'Phường', '002') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00085', 'Phường Phan Chu Trinh', 'Phường', '002') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00088', 'Phường Hàng Bài', 'Phường', '002') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00091', 'Phường Phú Thượng', 'Phường', '003') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00094', 'Phường Nhật Tân', 'Phường', '003') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00097', 'Phường Tứ Liên', 'Phường', '003') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00100', 'Phường Quảng An', 'Phường', '003') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00103', 'Phường Xuân La', 'Phường', '003') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00106', 'Phường Yên Phụ', 'Phường', '003') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00109', 'Phường Bưởi', 'Phường', '003') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00112', 'Phường Thụy Khuê', 'Phường', '003') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00115', 'Phường Thượng Thanh', 'Phường', '004') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00118', 'Phường Ngọc Thụy', 'Phường', '004') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00121', 'Phường Giang Biên', 'Phường', '004') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00124', 'Phường Đức Giang', 'Phường', '004') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00127', 'Phường Việt Hưng', 'Phường', '004') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00130', 'Phường Gia Thụy', 'Phường', '004') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00133', 'Phường Ngọc Lâm', 'Phường', '004') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00136', 'Phường Phúc Lợi', 'Phường', '004') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00139', 'Phường Bồ Đề', 'Phường', '004') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00145', 'Phường Long Biên', 'Phường', '004') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00148', 'Phường Thạch Bàn', 'Phường', '004') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00151', 'Phường Phúc Đồng', 'Phường', '004') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00154', 'Phường Cự Khối', 'Phường', '004') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00157', 'Phường Nghĩa Đô', 'Phường', '005') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00160', 'Phường Nghĩa Tân', 'Phường', '005') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00163', 'Phường Mai Dịch', 'Phường', '005') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00166', 'Phường Dịch Vọng', 'Phường', '005') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00167', 'Phường Dịch Vọng Hậu', 'Phường', '005') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00169', 'Phường Quan Hoa', 'Phường', '005') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00172', 'Phường Yên Hoà', 'Phường', '005') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00175', 'Phường Trung Hoà', 'Phường', '005') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00178', 'Phường Cát Linh', 'Phường', '006') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00181', 'Phường Văn Miếu - Quốc Tử Giám', 'Phường', '006') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00187', 'Phường Láng Thượng', 'Phường', '006') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00190', 'Phường Ô Chợ Dừa', 'Phường', '006') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00193', 'Phường Văn Chương', 'Phường', '006') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00196', 'Phường Hàng Bột', 'Phường', '006') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00199', 'Phường Láng Hạ', 'Phường', '006') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00202', 'Phường Khâm Thiên', 'Phường', '006') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00205', 'Phường Thổ Quan', 'Phường', '006') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00208', 'Phường Nam Đồng', 'Phường', '006') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00214', 'Phường Quang Trung', 'Phường', '006') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00217', 'Phường Trung Liệt', 'Phường', '006') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00226', 'Phường Phương Liên - Trung Tự', 'Phường', '006') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00229', 'Phường Kim Liên', 'Phường', '006') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00232', 'Phường Phương Mai', 'Phường', '006') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00235', 'Phường Thịnh Quang', 'Phường', '006') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00238', 'Phường Khương Thượng', 'Phường', '006') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00241', 'Phường Nguyễn Du', 'Phường', '007') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00244', 'Phường Bạch Đằng', 'Phường', '007') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00247', 'Phường Phạm Đình Hổ', 'Phường', '007') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00256', 'Phường Lê Đại Hành', 'Phường', '007') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00259', 'Phường Đồng Nhân', 'Phường', '007') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00262', 'Phường Phố Huế', 'Phường', '007') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00268', 'Phường Thanh Lương', 'Phường', '007') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00271', 'Phường Thanh Nhàn', 'Phường', '007') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00277', 'Phường Bách Khoa', 'Phường', '007') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00280', 'Phường Đồng Tâm', 'Phường', '007') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00283', 'Phường Vĩnh Tuy', 'Phường', '007') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00289', 'Phường Quỳnh Mai', 'Phường', '007') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00292', 'Phường Bạch Mai', 'Phường', '007') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00295', 'Phường Minh Khai', 'Phường', '007') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00298', 'Phường Trương Định', 'Phường', '007') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00301', 'Phường Thanh Trì', 'Phường', '008') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00304', 'Phường Vĩnh Hưng', 'Phường', '008') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00307', 'Phường Định Công', 'Phường', '008') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00310', 'Phường Mai Động', 'Phường', '008') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00313', 'Phường Tương Mai', 'Phường', '008') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00316', 'Phường Đại Kim', 'Phường', '008') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00319', 'Phường Tân Mai', 'Phường', '008') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00322', 'Phường Hoàng Văn Thụ', 'Phường', '008') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00325', 'Phường Giáp Bát', 'Phường', '008') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00328', 'Phường Lĩnh Nam', 'Phường', '008') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00331', 'Phường Thịnh Liệt', 'Phường', '008') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00334', 'Phường Trần Phú', 'Phường', '008') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00337', 'Phường Hoàng Liệt', 'Phường', '008') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00340', 'Phường Yên Sở', 'Phường', '008') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00343', 'Phường Nhân Chính', 'Phường', '009') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00346', 'Phường Thượng Đình', 'Phường', '009') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00349', 'Phường Khương Trung', 'Phường', '009') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00352', 'Phường Khương Mai', 'Phường', '009') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00355', 'Phường Thanh Xuân Trung', 'Phường', '009') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00358', 'Phường Phương Liệt', 'Phường', '009') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00364', 'Phường Khương Đình', 'Phường', '009') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00367', 'Phường Thanh Xuân Bắc', 'Phường', '009') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00373', 'Phường Hạ Đình', 'Phường', '009') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00376', 'Thị trấn Sóc Sơn', 'Thị trấn', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00379', 'Xã Bắc Sơn', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00382', 'Xã Minh Trí', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00385', 'Xã Hồng Kỳ', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00388', 'Xã Nam Sơn', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00391', 'Xã Trung Giã', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00394', 'Xã Tân Hưng', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00397', 'Xã Minh Phú', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00400', 'Xã Phù Linh', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00403', 'Xã Bắc Phú', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00406', 'Xã Tân Minh', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00409', 'Xã Quang Tiến', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00412', 'Xã Hiền Ninh', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00415', 'Xã Tân Dân', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00418', 'Xã Tiên Dược', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00421', 'Xã Việt Long', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00424', 'Xã Xuân Giang', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00427', 'Xã Mai Đình', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00430', 'Xã Đức Hoà', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00433', 'Xã Thanh Xuân', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00436', 'Xã Đông Xuân', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00439', 'Xã Kim Lũ', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00442', 'Xã Phú Cường', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00445', 'Xã Phú Minh', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00448', 'Xã Phù Lỗ', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00451', 'Xã Xuân Thu', 'Xã', '016') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00454', 'Thị trấn Đông Anh', 'Thị trấn', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00457', 'Xã Xuân Nộn', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00460', 'Xã Thuỵ Lâm', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00463', 'Xã Bắc Hồng', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00466', 'Xã Nguyên Khê', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00469', 'Xã Nam Hồng', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00472', 'Xã Tiên Dương', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00475', 'Xã Vân Hà', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00478', 'Xã Uy Nỗ', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00481', 'Xã Vân Nội', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00484', 'Xã Liên Hà', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00487', 'Xã Việt Hùng', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00490', 'Xã Kim Nỗ', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00493', 'Xã Kim Chung', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00496', 'Xã Dục Tú', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00499', 'Xã Đại Mạch', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00502', 'Xã Vĩnh Ngọc', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00505', 'Xã Cổ Loa', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00508', 'Xã Hải Bối', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00511', 'Xã Xuân Canh', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00514', 'Xã Võng La', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00517', 'Xã Tàm Xá', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00520', 'Xã Mai Lâm', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00523', 'Xã Đông Hội', 'Xã', '017') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00526', 'Thị trấn Yên Viên', 'Thị trấn', '018') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00529', 'Xã Yên Thường', 'Xã', '018') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00532', 'Xã Yên Viên', 'Xã', '018') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00535', 'Xã Ninh Hiệp', 'Xã', '018') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00541', 'Xã Thiên Đức', 'Xã', '018') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00544', 'Xã Phù Đổng', 'Xã', '018') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00550', 'Xã Lệ Chi', 'Xã', '018') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00553', 'Xã Cổ Bi', 'Xã', '018') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00556', 'Xã Đặng Xá', 'Xã', '018') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00562', 'Xã Phú Sơn', 'Xã', '018') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00565', 'Thị trấn Trâu Quỳ', 'Thị trấn', '018') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00568', 'Xã Dương Quang', 'Xã', '018') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00571', 'Xã Dương Xá', 'Xã', '018') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00577', 'Xã Đa Tốn', 'Xã', '018') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00580', 'Xã Kiêu Kỵ', 'Xã', '018') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00583', 'Xã Bát Tràng', 'Xã', '018') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00589', 'Xã Kim Đức', 'Xã', '018') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00592', 'Phường Cầu Diễn', 'Phường', '019') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00622', 'Phường Xuân Phương', 'Phường', '019') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00623', 'Phường Phương Canh', 'Phường', '019') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00625', 'Phường Mỹ Đình 1', 'Phường', '019') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00626', 'Phường Mỹ Đình 2', 'Phường', '019') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00628', 'Phường Tây Mỗ', 'Phường', '019') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00631', 'Phường Mễ Trì', 'Phường', '019') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00632', 'Phường Phú Đô', 'Phường', '019') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00634', 'Phường Đại Mỗ', 'Phường', '019') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00637', 'Phường Trung Văn', 'Phường', '019') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00640', 'Thị trấn Văn Điển', 'Thị trấn', '020') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00643', 'Xã Tân Triều', 'Xã', '020') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00646', 'Xã Thanh Liệt', 'Xã', '020') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00649', 'Xã Tả Thanh Oai', 'Xã', '020') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00652', 'Xã Hữu Hoà', 'Xã', '020') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00655', 'Xã Tam Hiệp', 'Xã', '020') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00658', 'Xã Tứ Hiệp', 'Xã', '020') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00661', 'Xã Yên Mỹ', 'Xã', '020') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00664', 'Xã Vĩnh Quỳnh', 'Xã', '020') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00667', 'Xã Ngũ Hiệp', 'Xã', '020') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00670', 'Xã Duyên Hà', 'Xã', '020') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00673', 'Xã Ngọc Hồi', 'Xã', '020') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00676', 'Xã Vạn Phúc', 'Xã', '020') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00679', 'Xã Đại áng', 'Xã', '020') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00682', 'Xã Liên Ninh', 'Xã', '020') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00685', 'Xã Đông Mỹ', 'Xã', '020') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00595', 'Phường Thượng Cát', 'Phường', '021') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00598', 'Phường Liên Mạc', 'Phường', '021') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00601', 'Phường Đông Ngạc', 'Phường', '021') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00602', 'Phường Đức Thắng', 'Phường', '021') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00604', 'Phường Thụy Phương', 'Phường', '021') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00607', 'Phường Tây Tựu', 'Phường', '021') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00610', 'Phường Xuân Đỉnh', 'Phường', '021') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00611', 'Phường Xuân Tảo', 'Phường', '021') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00613', 'Phường Minh Khai', 'Phường', '021') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00616', 'Phường Cổ Nhuế 1', 'Phường', '021') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00617', 'Phường Cổ Nhuế 2', 'Phường', '021') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00619', 'Phường Phú Diễn', 'Phường', '021') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('00620', 'Phường Phúc Diễn', 'Phường', '021') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('08973', 'Thị trấn Chi Đông', 'Thị trấn', '250') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('08974', 'Xã Đại Thịnh', 'Xã', '250') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('08977', 'Xã Kim Hoa', 'Xã', '250') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('08980', 'Xã Thạch Đà', 'Xã', '250') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('08983', 'Xã Tiến Thắng', 'Xã', '250') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('08986', 'Xã Tự Lập', 'Xã', '250') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('08989', 'Thị trấn Quang Minh', 'Thị trấn', '250') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('08992', 'Xã Thanh Lâm', 'Xã', '250') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('08995', 'Xã Tam Đồng', 'Xã', '250') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('08998', 'Xã Liên Mạc', 'Xã', '250') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09004', 'Xã Chu Phan', 'Xã', '250') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09007', 'Xã Tiến Thịnh', 'Xã', '250') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09010', 'Xã Mê Linh', 'Xã', '250') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09013', 'Xã Văn Khê', 'Xã', '250') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09016', 'Xã Hoàng Kim', 'Xã', '250') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09019', 'Xã Tiền Phong', 'Xã', '250') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09022', 'Xã Tráng Việt', 'Xã', '250') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09538', 'Phường Quang Trung', 'Phường', '268') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09541', 'Phường Mộ Lao', 'Phường', '268') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09542', 'Phường Văn Quán', 'Phường', '268') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09544', 'Phường Vạn Phúc', 'Phường', '268') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09551', 'Phường La Khê', 'Phường', '268') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09552', 'Phường Phú La', 'Phường', '268') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09553', 'Phường Phúc La', 'Phường', '268') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09556', 'Phường Hà Cầu', 'Phường', '268') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09562', 'Phường Yên Nghĩa', 'Phường', '268') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09565', 'Phường Kiến Hưng', 'Phường', '268') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09568', 'Phường Phú Lãm', 'Phường', '268') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09571', 'Phường Phú Lương', 'Phường', '268') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09886', 'Phường Dương Nội', 'Phường', '268') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10117', 'Phường Đồng Mai', 'Phường', '268') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10123', 'Phường Biên Giang', 'Phường', '268') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09574', 'Phường Ngô Quyền', 'Phường', '269') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09577', 'Phường Phú Thịnh', 'Phường', '269') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09586', 'Phường Sơn Lộc', 'Phường', '269') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09589', 'Phường Xuân Khanh', 'Phường', '269') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09592', 'Xã Đường Lâm', 'Xã', '269') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09595', 'Phường Viên Sơn', 'Phường', '269') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09598', 'Xã Xuân Sơn', 'Xã', '269') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09601', 'Phường Trung Hưng', 'Phường', '269') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09604', 'Xã Thanh Mỹ', 'Xã', '269') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09607', 'Phường Trung Sơn Trầm', 'Phường', '269') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09610', 'Xã Kim Sơn', 'Xã', '269') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09613', 'Xã Sơn Đông', 'Xã', '269') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09616', 'Xã Cổ Đông', 'Xã', '269') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09619', 'Thị trấn Tây Đằng', 'Thị trấn', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09625', 'Xã Phú Cường', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09628', 'Xã Cổ Đô', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09634', 'Xã Vạn Thắng', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09640', 'Xã Phong Vân', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09643', 'Xã Phú Đông', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09646', 'Xã Phú Hồng', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09649', 'Xã Phú Châu', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09652', 'Xã Thái Hòa', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09655', 'Xã Đồng Thái', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09658', 'Xã Phú Sơn', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09661', 'Xã Minh Châu', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09664', 'Xã Vật Lại', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09667', 'Xã Chu Minh', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09670', 'Xã Tòng Bạt', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09673', 'Xã Cẩm Lĩnh', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09676', 'Xã Sơn Đà', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09679', 'Xã Đông Quang', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09682', 'Xã Tiên Phong', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09685', 'Xã Thụy An', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09688', 'Xã Cam Thượng', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09691', 'Xã Thuần Mỹ', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09694', 'Xã Tản Lĩnh', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09697', 'Xã Ba Trại', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09700', 'Xã Minh Quang', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09703', 'Xã Ba Vì', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09706', 'Xã Vân Hòa', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09709', 'Xã Yên Bài', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09712', 'Xã Khánh Thượng', 'Xã', '271') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09715', 'Thị trấn Phúc Thọ', 'Thị trấn', '272') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09721', 'Xã Vân Phúc', 'Xã', '272') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09724', 'Xã Nam Hà', 'Xã', '272') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09727', 'Xã Xuân Đình', 'Xã', '272') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09733', 'Xã Sen Phương', 'Xã', '272') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09739', 'Xã Võng Xuyên', 'Xã', '272') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09742', 'Xã Tích Lộc', 'Xã', '272') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09745', 'Xã Long Thượng', 'Xã', '272') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09751', 'Xã Hát Môn', 'Xã', '272') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09757', 'Xã Thanh Đa', 'Xã', '272') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09760', 'Xã Trạch Mỹ Lộc', 'Xã', '272') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09763', 'Xã Phúc Hòa', 'Xã', '272') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09766', 'Xã Ngọc Tảo', 'Xã', '272') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09769', 'Xã Phụng Thượng', 'Xã', '272') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09772', 'Xã Tam Thuấn', 'Xã', '272') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09775', 'Xã Tam Hiệp', 'Xã', '272') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09778', 'Xã Hiệp Thuận', 'Xã', '272') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09781', 'Xã Liên Hiệp', 'Xã', '272') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09784', 'Thị trấn Phùng', 'Thị trấn', '273') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09787', 'Xã Trung Châu', 'Xã', '273') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09790', 'Xã Thọ An', 'Xã', '273') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09793', 'Xã Thọ Xuân', 'Xã', '273') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09796', 'Xã Hồng Hà', 'Xã', '273') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09799', 'Xã Liên Hồng', 'Xã', '273') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09802', 'Xã Liên Hà', 'Xã', '273') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09805', 'Xã Hạ Mỗ', 'Xã', '273') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09808', 'Xã Liên Trung', 'Xã', '273') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09811', 'Xã Phương Đình', 'Xã', '273') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09814', 'Xã Thượng Mỗ', 'Xã', '273') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09817', 'Xã Tân Hội', 'Xã', '273') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09820', 'Xã Tân Lập', 'Xã', '273') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09823', 'Xã Đan Phượng', 'Xã', '273') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09826', 'Xã Đồng Tháp', 'Xã', '273') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09829', 'Xã Song Phượng', 'Xã', '273') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09832', 'Thị trấn Trạm Trôi', 'Thị trấn', '274') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09835', 'Xã Đức Thượng', 'Xã', '274') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09838', 'Xã Minh Khai', 'Xã', '274') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09841', 'Xã Dương Liễu', 'Xã', '274') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09844', 'Xã Di Trạch', 'Xã', '274') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09847', 'Xã Đức Giang', 'Xã', '274') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09850', 'Xã Cát Quế', 'Xã', '274') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09853', 'Xã Kim Chung', 'Xã', '274') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09856', 'Xã Yên Sở', 'Xã', '274') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09859', 'Xã Sơn Đồng', 'Xã', '274') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09862', 'Xã Vân Canh', 'Xã', '274') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09865', 'Xã Đắc Sở', 'Xã', '274') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09868', 'Xã Lại Yên', 'Xã', '274') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09871', 'Xã Tiền Yên', 'Xã', '274') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09874', 'Xã Song Phương', 'Xã', '274') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09877', 'Xã An Khánh', 'Xã', '274') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09880', 'Xã An Thượng', 'Xã', '274') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09883', 'Xã Vân Côn', 'Xã', '274') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09889', 'Xã La Phù', 'Xã', '274') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09892', 'Xã Đông La', 'Xã', '274') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('04939', 'Xã Đông Xuân', 'Xã', '275') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09895', 'Thị trấn Quốc Oai', 'Thị trấn', '275') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09898', 'Xã Sài Sơn', 'Xã', '275') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09904', 'Xã Phượng Sơn', 'Xã', '275') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09907', 'Xã Ngọc Liệp', 'Xã', '275') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09910', 'Xã Ngọc Mỹ', 'Xã', '275') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09916', 'Xã Thạch Thán', 'Xã', '275') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09919', 'Xã Đồng Quang', 'Xã', '275') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09922', 'Xã Phú Cát', 'Xã', '275') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09925', 'Xã Tuyết Nghĩa', 'Xã', '275') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09928', 'Xã Liệp Nghĩa', 'Xã', '275') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09931', 'Xã Cộng Hòa', 'Xã', '275') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09934', 'Xã Hưng Đạo', 'Xã', '275') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09940', 'Xã Phú Mãn', 'Xã', '275') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09943', 'Xã Cấn Hữu', 'Xã', '275') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09949', 'Xã Hòa Thạch', 'Xã', '275') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09952', 'Xã Đông Yên', 'Xã', '275') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('04927', 'Xã Yên Trung', 'Xã', '276') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('04930', 'Xã Yên Bình', 'Xã', '276') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('04936', 'Xã Tiến Xuân', 'Xã', '276') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09955', 'Thị trấn Liên Quan', 'Thị trấn', '276') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09958', 'Xã Đại Đồng', 'Xã', '276') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09961', 'Xã Cẩm Yên', 'Xã', '276') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09964', 'Xã Lại Thượng', 'Xã', '276') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09967', 'Xã Phú Kim', 'Xã', '276') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09970', 'Xã Hương Ngải', 'Xã', '276') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09973', 'Xã Lam Sơn', 'Xã', '276') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09976', 'Xã Kim Quan', 'Xã', '276') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09982', 'Xã Bình Yên', 'Xã', '276') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09988', 'Xã Thạch Hoà', 'Xã', '276') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09991', 'Xã Cần Kiệm', 'Xã', '276') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('09997', 'Xã Phùng Xá', 'Xã', '276') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10000', 'Xã Tân Xã', 'Xã', '276') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10003', 'Xã Thạch Xá', 'Xã', '276') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10006', 'Xã Quang Trung', 'Xã', '276') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10009', 'Xã Hạ Bằng', 'Xã', '276') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10012', 'Xã Đồng Trúc', 'Xã', '276') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10015', 'Thị trấn Chúc Sơn', 'Thị trấn', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10018', 'Thị trấn Xuân Mai', 'Thị trấn', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10021', 'Xã Phụng Châu', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10024', 'Xã Tiên Phương', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10027', 'Xã Đông Sơn', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10030', 'Xã Đông Phương Yên', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10033', 'Xã Phú Nghĩa', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10039', 'Xã Trường Yên', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10042', 'Xã Ngọc Hòa', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10045', 'Xã Thủy Xuân Tiên', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10048', 'Xã Thanh Bình', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10051', 'Xã Trung Hòa', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10054', 'Xã Đại Yên', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10057', 'Xã Thụy Hương', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10060', 'Xã Tốt Động', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10063', 'Xã Lam Điền', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10066', 'Xã Tân Tiến', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10069', 'Xã Nam Phương Tiến', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10072', 'Xã Hợp Đồng', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10075', 'Xã Hoàng Văn Thụ', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10078', 'Xã Hoàng Diệu', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10081', 'Xã Hữu Văn', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10084', 'Xã Quảng Bị', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10087', 'Xã Mỹ Lương', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10090', 'Xã Thượng Vực', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10096', 'Xã Hồng Phú', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10099', 'Xã Trần Phú', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10102', 'Xã Văn Võ', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10105', 'Xã Đồng Lạc', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10108', 'Xã Hòa Phú', 'Xã', '277') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10114', 'Thị trấn Kim Bài', 'Thị trấn', '278') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10120', 'Xã Cự Khê', 'Xã', '278') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10126', 'Xã Bích Hòa', 'Xã', '278') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10129', 'Xã Mỹ Hưng', 'Xã', '278') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10132', 'Xã Cao Viên', 'Xã', '278') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10135', 'Xã Bình Minh', 'Xã', '278') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10138', 'Xã Tam Hưng', 'Xã', '278') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10141', 'Xã Thanh Cao', 'Xã', '278') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10144', 'Xã Thanh Thùy', 'Xã', '278') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10147', 'Xã Thanh Mai', 'Xã', '278') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10150', 'Xã Thanh Văn', 'Xã', '278') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10153', 'Xã Đỗ Động', 'Xã', '278') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10156', 'Xã Kim An', 'Xã', '278') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10159', 'Xã Kim Thư', 'Xã', '278') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10162', 'Xã Phương Trung', 'Xã', '278') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10165', 'Xã Tân Ước', 'Xã', '278') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10168', 'Xã Dân Hòa', 'Xã', '278') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10171', 'Xã Liên Châu', 'Xã', '278') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10174', 'Xã Cao Xuân Dương', 'Xã', '278') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10180', 'Xã Hồng Dương', 'Xã', '278') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10183', 'Thị trấn Thường Tín', 'Thị trấn', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10186', 'Xã Ninh Sở', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10189', 'Xã Nhị Khê', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10192', 'Xã Duyên Thái', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10195', 'Xã Khánh Hà', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10198', 'Xã Hòa Bình', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10201', 'Xã Văn Bình', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10204', 'Xã Hiền Giang', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10207', 'Xã Hồng Vân', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10210', 'Xã Vân Tảo', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10213', 'Xã Liên Phương', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10216', 'Xã Văn Phú', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10219', 'Xã Tự Nhiên', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10222', 'Xã Tiền Phong', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10225', 'Xã Hà Hồi', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10231', 'Xã Nguyễn Trãi', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10234', 'Xã Quất Động', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10237', 'Xã Chương Dương', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10240', 'Xã Tân Minh', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10243', 'Xã Lê Lợi', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10246', 'Xã Thắng Lợi', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10249', 'Xã Dũng Tiến', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10255', 'Xã Nghiêm Xuyên', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10258', 'Xã Tô Hiệu', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10261', 'Xã Văn Tự', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10264', 'Xã Vạn Nhất', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10267', 'Xã Minh Cường', 'Xã', '279') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10270', 'Thị trấn Phú Minh', 'Thị trấn', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10273', 'Thị trấn Phú Xuyên', 'Thị trấn', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10276', 'Xã Hồng Minh', 'Xã', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10279', 'Xã Phượng Dực', 'Xã', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10282', 'Xã Nam Tiến', 'Xã', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10291', 'Xã Văn Hoàng', 'Xã', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10294', 'Xã Phú Túc', 'Xã', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10300', 'Xã Hồng Thái', 'Xã', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10303', 'Xã Hoàng Long', 'Xã', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10312', 'Xã Nam Phong', 'Xã', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10315', 'Xã Tân Dân', 'Xã', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10318', 'Xã Quang Hà', 'Xã', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10321', 'Xã Chuyên Mỹ', 'Xã', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10324', 'Xã Khai Thái', 'Xã', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10327', 'Xã Phúc Tiến', 'Xã', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10330', 'Xã Vân Từ', 'Xã', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10333', 'Xã Tri Thủy', 'Xã', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10336', 'Xã Đại Xuyên', 'Xã', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10339', 'Xã Phú Yên', 'Xã', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10342', 'Xã Bạch Hạ', 'Xã', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10345', 'Xã Quang Lãng', 'Xã', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10348', 'Xã Châu Can', 'Xã', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10351', 'Xã Minh Tân', 'Xã', '280') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10354', 'Thị trấn Vân Đình', 'Thị trấn', '281') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10363', 'Xã Hoa Viên', 'Xã', '281') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10366', 'Xã Quảng Phú Cầu', 'Xã', '281') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10369', 'Xã Trường Thịnh', 'Xã', '281') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10375', 'Xã Liên Bạt', 'Xã', '281') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10378', 'Xã Cao Sơn Tiến', 'Xã', '281') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10384', 'Xã Phương Tú', 'Xã', '281') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10387', 'Xã Trung Tú', 'Xã', '281') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10390', 'Xã Đồng Tân', 'Xã', '281') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10393', 'Xã Tảo Dương Văn', 'Xã', '281') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10396', 'Xã Thái Hòa', 'Xã', '281') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10399', 'Xã Minh Đức', 'Xã', '281') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10402', 'Xã Trầm Lộng', 'Xã', '281') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10411', 'Xã Kim Đường', 'Xã', '281') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10417', 'Xã Hòa Phú', 'Xã', '281') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10423', 'Xã Đại Hùng', 'Xã', '281') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10426', 'Xã Đông Lỗ', 'Xã', '281') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10429', 'Xã Phù Lưu', 'Xã', '281') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10432', 'Xã Đại Cường', 'Xã', '281') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10435', 'Xã Bình Lưu Quang', 'Xã', '281') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10441', 'Thị trấn Đại Nghĩa', 'Thị trấn', '282') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10444', 'Xã Đồng Tâm', 'Xã', '282') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10447', 'Xã Thượng Lâm', 'Xã', '282') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10450', 'Xã Tuy Lai', 'Xã', '282') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10453', 'Xã Phúc Lâm', 'Xã', '282') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10459', 'Xã Mỹ Xuyên', 'Xã', '282') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10462', 'Xã An Mỹ', 'Xã', '282') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10465', 'Xã Hồng Sơn', 'Xã', '282') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10468', 'Xã Lê Thanh', 'Xã', '282') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10471', 'Xã Xuy Xá', 'Xã', '282') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10474', 'Xã Phùng Xá', 'Xã', '282') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10477', 'Xã Phù Lưu Tế', 'Xã', '282') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10480', 'Xã Đại Hưng', 'Xã', '282') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10483', 'Xã Vạn Tín', 'Xã', '282') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10489', 'Xã Hương Sơn', 'Xã', '282') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10492', 'Xã Hùng Tiến', 'Xã', '282') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10495', 'Xã An Tiến', 'Xã', '282') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10498', 'Xã Hợp Tiến', 'Xã', '282') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10501', 'Xã Hợp Thanh', 'Xã', '282') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.vn_wards (id, name, level, district_id) VALUES ('10504', 'Xã An Phú', 'Xã', '282') ON CONFLICT (id) DO NOTHING;
